version: 0.2
env: 
  parameter-store: 
    MONGODBURL: "/ankit/mongo_url"
phases:
  pre_build:
    commands:
       - npm install
  build:
    commands:
       - sed -i 's/localhost/'$MONGODBURL'/' app.js

artifacts:
  files:
    - '**/*'
